apiVersion: v1
kind: Namespace
metadata:
  name: genteelbeacon

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gildedgateway
  namespace: genteelbeacon
  labels:
    app: gildedgateway
    schildwaechter: genteelbeacon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gildedgateway
  template:
    metadata:
      labels:
        app: gildedgateway
    spec:
      containers:
        - name: genteelbeacon
          image: schildwaechter/genteelbeacon:main
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "10m"
          livenessProbe:
            httpGet:
              path: /livez
              port: servingport
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: servingport
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
          envFrom:
            - configMapRef:
                name: gildedgateway
          ports:
            - name: servingport
              containerPort: 1333
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gildedgateway
  namespace: genteelbeacon
data:
  APP_NAME: "Gilded Gateway"
  BACKEND: "http://regencyrelay:1333"
  OTLPHTTP_ENDPOINT: "otelcol-opentelemetry-collector.otel:4318"
---
apiVersion: v1
kind: Service
metadata:
  name: gildedgateway
  namespace: genteelbeacon
spec:
  selector:
    app: gildedgateway
  ports:
    - protocol: TCP
      port: 1333
      targetPort: 1333

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: regencyrelay
  namespace: genteelbeacon
  labels:
    app: regencyrelay
    schildwaechter: genteelbeacon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: regencyrelay
  template:
    metadata:
      labels:
        app: regencyrelay
    spec:
      containers:
        - name: genteelbeacon
          image: schildwaechter/genteelbeacon:main
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "10m"
          livenessProbe:
            httpGet:
              path: /livez
              port: servingport
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: servingport
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
          envFrom:
            - configMapRef:
                name: regencyrelay
          ports:
            - name: servingport
              containerPort: 1333
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: regencyrelay
  namespace: genteelbeacon
data:
  APP_NAME: "Regency Relay"
  BACKEND: "http://elegantendeavors:1333"
  OTLPHTTP_ENDPOINT: "otelcol-opentelemetry-collector.otel:4318"
---
apiVersion: v1
kind: Service
metadata:
  name: regencyrelay
  namespace: genteelbeacon
spec:
  selector:
    app: regencyrelay
  ports:
    - protocol: TCP
      port: 1333
      targetPort: 1333

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elegantendeavors
  namespace: genteelbeacon
  labels:
    app: elegantendeavors
    schildwaechter: genteelbeacon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elegantendeavors
  template:
    metadata:
      labels:
        app: elegantendeavors
    spec:
      containers:
        - name: genteelbeacon
          image: schildwaechter/genteelbeacon:main
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "10m"
          livenessProbe:
            httpGet:
              path: /livez
              port: servingport
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: servingport
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
          envFrom:
            - configMapRef:
                name: elegantendeavors
          ports:
            - name: servingport
              containerPort: 1333
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elegantendeavors
  namespace: genteelbeacon
data:
  APP_NAME: "Elegant Endeavors, Esq."
  OTLPHTTP_ENDPOINT: "otelcol-opentelemetry-collector.otel:4318"
---
apiVersion: v1
kind: Service
metadata:
  name: elegantendeavors
  namespace: genteelbeacon
spec:
  selector:
    app: elegantendeavors
  ports:
    - protocol: TCP
      port: 1333
      targetPort: 1333
