apiVersion: v1
kind: Namespace
metadata:
  name: genteelbeacon

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gildedgateway
  namespace: genteelbeacon
  labels:
    app: gildedgateway
    genteelbeacon: gildedgateway
    genteelrole: relay
    schildwaechter: genteelbeacon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gildedgateway
  template:
    metadata:
      labels:
        app: gildedgateway
        genteelbeacon: gildedgateway
        genteelrole: relay
        schildwaechter: genteelbeacon
    spec:
      containers:
        - name: genteelbeacon
          image: schildwaechter/genteelbeacon:main
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "10m"
          livenessProbe:
            httpGet:
              path: /livez
              port: servingport
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: servingport
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
          envFrom:
            - configMapRef:
                name: gildedgateway
          ports:
            - name: servingport
              containerPort: 1333
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gildedgateway
  namespace: genteelbeacon
data:
  APP_NAME: "Gilded Gateway"
  GENTEEL_CLOCK: "http://velvettimepeace:1333"
  OTLPHTTP_ENDPOINT: "otelcol-opentelemetry-collector.otel:4318"
---
apiVersion: v1
kind: Service
metadata:
  name: gildedgateway
  namespace: genteelbeacon
spec:
  selector:
    app: gildedgateway
  ports:
    - protocol: TCP
      port: 1333
      targetPort: 1333

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: velvettimepeace
  namespace: genteelbeacon
  labels:
    app: velvettimepeace
    genteelbeacon: velvettimepeace
    genteelrole: clock
    schildwaechter: genteelbeacon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velvettimepeace
  template:
    metadata:
      labels:
        app: velvettimepeace
        genteelbeacon: velvettimepeace
        genteelrole: clock
        schildwaechter: genteelbeacon
    spec:
      containers:
        - name: genteelbeacon
          image: schildwaechter/genteelbeacon:main
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "10m"
          livenessProbe:
            httpGet:
              path: /livez
              port: servingport
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: servingport
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
          envFrom:
            - configMapRef:
                name: velvettimepeace
          ports:
            - name: servingport
              containerPort: 1333
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: velvettimepeace
  namespace: genteelbeacon
data:
  APP_NAME: "Velvet Timepeace"
  OTLPHTTP_ENDPOINT: "otelcol-opentelemetry-collector.otel:4318"
---
apiVersion: v1
kind: Service
metadata:
  name: velvettimepeace
  namespace: genteelbeacon
spec:
  selector:
    app: velvettimepeace
  ports:
    - protocol: TCP
      port: 1333
      targetPort: 1333
