apiVersion: v1
kind: Namespace
metadata:
  name: genteelbeacon

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gaslightparlour
  namespace: genteelbeacon
  labels:
    app: gaslightparlour
    genteelbeacon: gaslightparlour
    genteelrole: relay
    schildwaechter: genteelbeacon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gaslightparlour
  template:
    metadata:
      labels:
        app: gaslightparlour
        genteelbeacon: gaslightparlour
        genteelrole: relay
        schildwaechter: genteelbeacon
    spec:
      containers:
        - name: genteelbeacon
          image: schildwaechter/genteelbeacon:main
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "10m"
          livenessProbe:
            httpGet:
              path: /livez
              port: servingport
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: servingport
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
          envFrom:
            - configMapRef:
                name: gaslightparlour
          ports:
            - name: servingport
              containerPort: 1333
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gaslightparlour
  namespace: genteelbeacon
  labels:
    app: gaslightparlour
    genteelbeacon: gaslightparlour
data:
  GENTEEL_NAME: "Gaslight Parlour"
  GENTEEL_ROLE: "telegraphist"
  GENTEEL_CLOCK: "http://velvettimepiece:1333"
  OTLPHTTP_ENDPOINT: "otelcol-opentelemetry-collector.otel:4318"
---
apiVersion: v1
kind: Service
metadata:
  name: gaslightparlour
  namespace: genteelbeacon
  labels:
    app: gaslightparlour
    genteelbeacon: gaslightparlour
spec:
  selector:
    app: gaslightparlour
  ports:
    - protocol: TCP
      port: 1333
      targetPort: 1333

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: velvettimepiece
  namespace: genteelbeacon
  labels:
    app: velvettimepiece
    genteelbeacon: velvettimepiece
    genteelrole: clock
    schildwaechter: genteelbeacon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velvettimepiece
  template:
    metadata:
      labels:
        app: velvettimepiece
        genteelbeacon: velvettimepiece
        genteelrole: clock
        schildwaechter: genteelbeacon
    spec:
      containers:
        - name: genteelbeacon
          image: schildwaechter/genteelbeacon:main
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "10m"
          livenessProbe:
            httpGet:
              path: /livez
              port: servingport
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: servingport
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
          envFrom:
            - configMapRef:
                name: velvettimepiece
          ports:
            - name: servingport
              containerPort: 1333
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: velvettimepiece
  namespace: genteelbeacon
  labels:
    app: velvettimepiece
    genteelbeacon: velvettimepiece
data:
  GENTEEL_NAME: "Velvet timepiece"
  GENTEEL_ROLE: "clock"
  OTLPHTTP_ENDPOINT: "otelcol-opentelemetry-collector.otel:4318"
---
apiVersion: v1
kind: Service
metadata:
  name: velvettimepiece
  namespace: genteelbeacon
  labels:
    app: velvettimepiece
    genteelbeacon: velvettimepiece
spec:
  selector:
    app: velvettimepiece
  ports:
    - protocol: TCP
      port: 1333
      targetPort: 1333
