# Genteel Beacon - Grumpy Gearsmith
# Copyright Carsten Thiel 2025
#
# SPDX-Identifier: Apache-2.0

apiVersion: v1
kind: ServiceAccount
metadata:
  name: grumpygearsmith
  namespace: genteelbeacon
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grumpygearsmith
  namespace: genteelbeacon
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grumpygearsmith
  namespace: genteelbeacon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grumpygearsmith
subjects:
  - kind: ServiceAccount
    name: grumpygearsmith
    namespace: genteelbeacon
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grumpygearsmith
  namespace: genteelbeacon
  labels:
    app: grumpygearsmith
    schildwaechter: genteelbeacon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grumpygearsmith
  template:
    metadata:
      labels:
        app: grumpygearsmith
    spec:
      containers:
        - name: grumpygearsmith
          image: schildwaechter/genteelbeacon:main
          command: ["/grumpygearsmith"]
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "10m"
          ports:
            - name: http
              containerPort: 8080
      serviceAccountName: grumpygearsmith
---
apiVersion: v1
kind: Service
metadata:
  name: grumpygearsmith
  namespace: genteelbeacon
spec:
  selector:
    app: grumpygearsmith
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
