# Genteel Beacon - Grumpy Gearsmith
# Copyright Carsten Thiel 2025
#
# SPDX-Identifier: Apache-2.0

apiVersion: v1
kind: ServiceAccount
metadata:
  name: grumpygearsmith
  namespace: genteelbeacon
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grumpygearsmith
  namespace: genteelbeacon
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grumpygearsmith
  namespace: genteelbeacon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grumpygearsmith
subjects:
  - kind: ServiceAccount
    name: grumpygearsmith
    namespace: genteelbeacon
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grumpygearsmith
  namespace: genteelbeacon
  labels:
    app: grumpygearsmith
    genteelbeacon: grumpygearsmith
    schildwaechter: genteelbeacon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grumpygearsmith
  template:
    metadata:
      labels:
        app: grumpygearsmith
        genteelbeacon: grumpygearsmith
    spec:
      volumes:
        - name: cert-volume
          secret:
            secretName: grumpygearsmith
      containers:
        - name: genteelbeacon
          image: schildwaechter/genteelbeacon:main
          imagePullPolicy: Always
          env:
            - name: GENTEEL_ROLE
              value: "gearsmith"
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "10m"
          ports:
            - name: https
              containerPort: 6443
          volumeMounts:
            - name: cert-volume
              readOnly: true
              mountPath: /cert
      serviceAccountName: grumpygearsmith
---
apiVersion: v1
kind: Service
metadata:
  name: grumpygearsmith
  namespace: genteelbeacon
  labels:
    app: grumpygearsmith
    genteelbeacon: grumpygearsmith
spec:
  selector:
    app: grumpygearsmith
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: https

---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.custom.metrics.k8s.io
spec:
  insecureSkipTLSVerify: true
  group: custom.metrics.k8s.io
  groupPriorityMinimum: 1000
  versionPriority: 5
  service:
    name: grumpygearsmith
    namespace: genteelbeacon
  version: v1beta1
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gaslightparlour
  namespace: genteelbeacon
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gaslightparlour
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Object
      object:
        describedObject:
          kind: Service
          name: gaslightparlour
        metric:
          name: inkvalue
        target:
          type: AverageValue
          averageValue: "80"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: velvettimepiece
  namespace: genteelbeacon
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: velvettimepiece
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Object
      object:
        describedObject:
          kind: Service
          name: velvettimepiece
        metric:
          name: gearvalue
        target:
          type: AverageValue
          averageValue: "80"
