mode: deployment
image:
  repository: otel/opentelemetry-collector-contrib

replicaCount: 1

ports:
  jaeger-compact:
    enabled: false
  jaeger-thrift:
    enabled: false
  jaeger-grpc:
    enabled: false
  zipkin:
    enabled: false

config:
  extensions:
    health_check:
      endpoint: 0.0.0.0:13133
    basicauth/client:
      client_auth:
        username: "PLACEHOLDER"
        password: "PLACEHOLDER"

  receivers:
    jaeger: null
    prometheus: null
    zipkin: null
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

  processors:
    transform/add_schildwaechter_attributes:
      # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor
      error_mode: ignore
      trace_statements:
        - context: span
          statements:
            - set(span.attributes["schildwaechter"], "genteelbeacon")
        - context: spanevent
          statements:
            - set(spanevent.attributes["schildwaechter"], "genteelbeacon")
      metric_statements:
        - context: datapoint
          statements:
            - set(datapoint.attributes["schildwaechter"], "genteelbeacon")
      log_statements:
        - context: scope
          statements:
            - set(scope.attributes["schildwaechter"], "genteelbeacon")
        - context: log
          statements:
            - set(log.attributes["schildwaechter"], "genteelbeacon")

  exporters:
    otlphttp:
      auth:
        authenticator: basicauth/client
      endpoint: "PLACEHOLDER"
      tls:
        insecure: true

  service:
    extensions: [basicauth/client, health_check]
    pipelines:
      traces:
        receivers: [otlp]
        processors: [transform/add_schildwaechter_attributes]
        exporters: [otlphttp]
      metrics:
        receivers: [otlp]
        processors: [transform/add_schildwaechter_attributes]
        exporters: [otlphttp]
      logs:
        receivers: [otlp]
        processors: [transform/add_schildwaechter_attributes]
        exporters: [otlphttp]
